### ISSUE TITLE
Use rope instead of tensile

### ISSUE THREAD

**Issue by suezere** [cohnt/6.8210-Final-Project-Lifting-Heavy-Objects-with-Teams-of-Quadrotors#1]
Hi, I want to use a chain of rigid bodies connected by ball joints to  replace the tensile module for better flexibility results. There are somany states(drones, ropes attached with rigid bodies). I want to know  how to split controller into drones(For example, when I use lqr for control, the dimension of Q is equal to the number of states, and I want the dimension of Q to be related only to the state of the drone and not to the state of the rope). And also I'm wondering if this is modelled in such a way that the direction and value of the rope pull can be read out directly.
Thanks!

**Comment by cohnt** [comment]
It seems like there are a few different questions here, so I'll try to answer them individually.

1. Using a chain of rigid bodies. I know that some other students in the class looked into this, but the modeling ended up being very complex, and they ended up using a single rigid body to connect them. You can find a video of their project presentation [here](https://youtu.be/9YRMjxojBgc?si=cpJJFdCT5GATAbaV&t=1436), but I don't know if the code is available online. It looks like someone did something similar in [this Stackoverflow post](https://stackoverflow.com/questions/77110625/split-controller-into-individual-system-in-drake).
2. Splitting the controllers. That same Stackoverflow post talks about how to do so.
3. Since we're passing information about the direction and value of the rope pull between ports, you can always read the value for a given context. Check the [Drake documentation](https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_output_port.html#abab8fb340a13be101704b48e46c12724). If you want to include that as an input to your controller, you could potentially add that as another state to pass into your LQR controller, although I haven't tried something like that before.

**Comment by suezere** [comment]
Thank you fot your help!
